import { useState, type FormEvent } from 'react'
import { Check, Eye, Play, Search, X } from 'lucide-react'
import { useRentalData } from '../../context/RentalDataContext'
import type { Reservation, StartRentalInput } from '../../types/rental'
import { Empty, Field, Modal, PageHeader, StatusBadge } from '../../components/admin/AdminUI'

const statusTone = (status: Reservation['status']) => status === 'Acceptée' ? 'green' : status === 'En attente' ? 'amber' : status === 'Refusée' ? 'red' : 'slate'
export default function DashboardReservationsPage() {
  const { reservations, vehicles, changeReservationStatus, startRental, loading, hasConflict } = useRentalData()
  const [search, setSearch] = useState(''); const [detail, setDetail] = useState<Reservation | null>(null); const [pickup, setPickup] = useState<Reservation | null>(null); const [message, setMessage] = useState('')
  const filtered = reservations.filter((item) => `${item.clientName} ${item.phone} ${item.id}`.toLowerCase().includes(search.toLowerCase())).sort((a, b) => b.createdAt.localeCompare(a.createdAt))
  const act = async (reservation: Reservation, status: Reservation['status']) => { if (!window.confirm(`${status === 'Acceptée' ? 'Accepter' : 'Refuser'} cette réservation ?`)) return; try { await changeReservationStatus(reservation.id, status); setMessage(`Réservation ${status.toLowerCase()}.`) } catch (error) { setMessage(error instanceof Error ? error.message : 'Erreur') } }
  return <div className="space-y-6"><PageHeader eyebrow="Commandes clients" title="Réservations" />{message && <div className="rounded-2xl bg-blue-50 px-5 py-4 text-sm font-medium text-blue-800">{message}</div>}
    <div className="rounded-3xl bg-white p-4 shadow-soft"><div className="relative max-w-md"><Search className="absolute left-4 top-1/2 -translate-y-1/2 text-slate-400" size={18}/><input value={search} onChange={(e)=>setSearch(e.target.value)} placeholder="Rechercher un client, téléphone ou numéro…" className="w-full bg-slate-50 pl-11 text-slate-900"/></div></div>
    <div className="overflow-hidden rounded-3xl bg-white shadow-soft"><div className="overflow-x-auto"><table className="min-w-[1250px] w-full text-left"><thead className="bg-slate-50"><tr>{['N° réservation','Date','Client','Téléphone','Véhicule','Début','Fin','Jours','Prix total','Paiement','Statut','Actions'].map(x=><th key={x} className="px-4 py-4 text-xs font-bold uppercase tracking-wide text-slate-500">{x}</th>)}</tr></thead><tbody>{filtered.map(item=>{const vehicle=vehicles.find(v=>v.id===item.vehicleId);return <tr key={item.id} className="border-t border-slate-100 text-sm text-slate-700"><td className="px-4 py-4 font-semibold">RES-{item.id.slice(-6).toUpperCase()}</td><td className="px-4 py-4">{new Date(item.createdAt).toLocaleDateString('fr-FR')}</td><td className="px-4 py-4 font-semibold text-slate-950">{item.clientName}</td><td className="px-4 py-4">{item.phone}</td><td className="px-4 py-4">{vehicle?.brand} {vehicle?.model}</td><td className="px-4 py-4">{item.startDate}</td><td className="px-4 py-4">{item.endDate}</td><td className="px-4 py-4">{item.days}</td><td className="px-4 py-4 font-semibold">{item.totalPrice.toLocaleString()} DA</td><td className="px-4 py-4">{item.paymentMethod||'—'}</td><td className="px-4 py-4"><StatusBadge tone={statusTone(item.status)}>{item.status}</StatusBadge>{hasConflict(item)&&item.status==='En attente'&&<p className="mt-1 text-xs text-rose-600">Conflit de dates</p>}</td><td className="px-4 py-4"><div className="flex gap-2"><button onClick={()=>setDetail(item)} className="rounded-xl bg-slate-100 p-2" title="Voir"><Eye size={16}/></button>{item.status==='En attente'&&<><button onClick={()=>act(item,'Acceptée')} className="rounded-xl bg-emerald-100 p-2 text-emerald-700" title="Accepter"><Check size={16}/></button><button onClick={()=>act(item,'Refusée')} className="rounded-xl bg-rose-100 p-2 text-rose-700" title="Refuser"><X size={16}/></button></>}{item.status==='Acceptée'&&<button onClick={()=>setPickup(item)} className="inline-flex items-center gap-1 rounded-xl bg-blue-600 px-3 py-2 text-xs font-bold text-white"><Play size={15}/> Véhicule récupéré</button>}</div></td></tr>})}</tbody></table></div>{!loading&&!filtered.length&&<Empty>Aucune réservation reçue.</Empty>}</div>
    {detail&&<Modal title="Détails de la réservation" onClose={()=>setDetail(null)}><div className="grid gap-4 sm:grid-cols-2 text-sm text-slate-700">{Object.entries({Client:detail.clientName,Téléphone:detail.phone,Email:detail.email,Adresse:detail.address,Permis:detail.licenseNumber,'Lieu départ':detail.pickupLocation,'Lieu retour':detail.returnLocation,Message:detail.message||'—'}).map(([k,v])=><div key={k} className="rounded-2xl bg-slate-50 p-4"><p className="text-xs text-slate-500">{k}</p><p className="mt-1 font-semibold">{v}</p></div>)}</div></Modal>}
    {pickup&&<StartRentalModal reservation={pickup} onClose={()=>setPickup(null)} onSubmit={async input=>{await startRental(pickup,input);setPickup(null);setMessage('Location démarrée. Le véhicule est maintenant loué.')}}/>}
  </div>
}
function StartRentalModal({reservation,onClose,onSubmit}:{reservation:Reservation;onClose:()=>void;onSubmit:(input:StartRentalInput)=>Promise<void>}){
  const [form,setForm]=useState<StartRentalInput>({startMileage:0,actualStartDate:new Date().toISOString().slice(0,10),actualStartTime:new Date().toTimeString().slice(0,5),rentalPrice:reservation.totalPrice,amountPaid:0,deposit:0,fuelStart:'Plein',departureCondition:'Bon état',notes:''}); const [error,setError]=useState('')
  const change=(key:keyof StartRentalInput,value:string|number)=>setForm(v=>({...v,[key]:value})); const submit=async(e:FormEvent)=>{e.preventDefault();try{await onSubmit(form)}catch(err){setError(err instanceof Error?err.message:'Erreur')}}
  return <Modal title="Client a récupéré le véhicule" onClose={onClose}><form onSubmit={submit} className="grid gap-5 sm:grid-cols-2"><Field label="Kilométrage départ *"><input required min="0" type="number" value={form.startMileage} onChange={e=>change('startMileage',+e.target.value)} className="w-full text-slate-900"/></Field><Field label="Montant location *"><input required min="0" type="number" value={form.rentalPrice} onChange={e=>change('rentalPrice',+e.target.value)} className="w-full text-slate-900"/></Field><Field label="Date réelle départ *"><input required type="date" value={form.actualStartDate} onChange={e=>change('actualStartDate',e.target.value)} className="w-full text-slate-900"/></Field><Field label="Heure départ *"><input required type="time" value={form.actualStartTime} onChange={e=>change('actualStartTime',e.target.value)} className="w-full text-slate-900"/></Field><Field label="Montant payé"><input min="0" type="number" value={form.amountPaid} onChange={e=>change('amountPaid',+e.target.value)} className="w-full text-slate-900"/></Field><Field label="Reste à payer"><input readOnly value={Math.max(0,form.rentalPrice-form.amountPaid)} className="w-full bg-slate-100 text-slate-900"/></Field><Field label="Caution"><input min="0" type="number" value={form.deposit} onChange={e=>change('deposit',+e.target.value)} className="w-full text-slate-900"/></Field><Field label="Carburant départ"><select value={form.fuelStart} onChange={e=>change('fuelStart',e.target.value)} className="w-full text-slate-900">{['Plein','3/4','1/2','1/4','Réserve'].map(x=><option key={x}>{x}</option>)}</select></Field><Field label="État au départ"><input required value={form.departureCondition} onChange={e=>change('departureCondition',e.target.value)} className="w-full text-slate-900"/></Field><Field label="Notes"><textarea value={form.notes} onChange={e=>change('notes',e.target.value)} className="w-full text-slate-900"/></Field>{error&&<p className="sm:col-span-2 text-sm text-rose-600">{error}</p>}<button className="btn-primary sm:col-span-2">Confirmer le départ</button></form></Modal>
}
